### ISSUE TITLE
Actual Setup

### ISSUE THREAD

**Issue by grempa** [feinersaft/symfony-ddev-setup#1]
Is there a update on the code? Would really be interested in such a setup, as i dont want to install an webstack locally/manually.

**Comment by feinersaft** [comment]
Hi, not yet. But I will think about picking it up again.

**Comment by feinersaft** [comment]
Now there is a quickstart for DDEV: [https://ddev.readthedocs.io/en/stable/users/quickstart/#symfony](https://ddev.readthedocs.io/en/stable/users/quickstart/#symfony)

Maybe this is what we're looking for after all :)
